Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile('C:\Antigravity_proyectos\Lector e IDE\LectorGlobalApp\logo sin fondo.png')
$bmp = New-Object System.Drawing.Bitmap($img, 256, 256)
$icoPath = 'C:\Antigravity_proyectos\Lector e IDE\LectorGlobalApp\logo.ico'
$fs = New-Object System.IO.FileStream($icoPath, [System.IO.FileMode]::Create)
$bw = New-Object System.IO.BinaryWriter($fs)
$bw.Write([int16]0)
$bw.Write([int16]1)
$bw.Write([int16]1)
$bw.Write([byte]0)
$bw.Write([byte]0)
$bw.Write([byte]0)
$bw.Write([byte]0)
$bw.Write([int16]1)
$bw.Write([int16]32)
$ms = New-Object System.IO.MemoryStream
$bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
$bw.Write([int]$ms.Length)
$bw.Write([int]22)
$bw.Write($ms.ToArray())
$bw.Flush()
$bw.Close()
$fs.Close()
$img.Dispose()
$bmp.Dispose()
$ms.Dispose()
